apiVersion: v1
kind: Service
metadata:
  name: payment-service
  annotations:
    cloud.google.com/backend-config: '{"default": "payment-backendconfig"}'
  # cloud.google.com/neg: '{"serverless": {"region": "us-central1"}}'

spec:
  type: NodePort
  selector:
    app: payment-service
  ports:
    - port:  80
      targetPort: 8080