apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: us-central1-docker.pkg.dev/ecom-project-468216/ecomrepo/product-service:v1
          ports:
          - containerPort: 8080
          env:
            - name: AUTH_SERVICE_URL
              value: "http://auth-service.default.svc.cluster.local/auth/validate"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

