apiVersion: v1
kind: Service
metadata:
  name: product-service-v2
  annotations:
    cloud.google.com/backend-config: '{"default": "product-backendconfig-v2"}'
spec:
  type: NodePort
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port:  80
      targetPort: 8080
