apiVersion: v1
kind: Service
metadata:
  name: order-service
  annotations:
    cloud.google.com/backend-config: '{"default": "order-backendconfig"}'
spec:
  type: NodePort
  selector:
    app: order-service
  ports:
    - port:  80
      targetPort: 8080