apiVersion: v1
kind: Service
metadata:
  name: auth-service
  annotations:
    cloud.google.com/backend-config: '{"default": "auth-backendconfig"}'
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - port:  80
      targetPort: 8080
